6664949: debug versions of cvm should not require JNI dlls to have the _g suffix
I changed the exception message to include the full name of the library, and not just the root name, so it is now more obvious what cvm is looking for when you have a debug/non-debug mismatch between cvm and the name of the dll. For example:

java.lang.UnsatisfiedLinkError: no libtestjni_g.so in java.library.path
	at java.lang.ClassLoader.loadLibraryInternal(Ljava/lang/Class;Ljava/lang/String;ZZ)Ljava/lang/Object;(ClassLoader.java:1653)
	at java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V(ClassLoader.java:1537)
	at java.lang.Runtime.loadLibrary0(Ljava/lang/Class;Ljava/lang/String;)V(Runtime.java:878)
	at java.lang.System.loadLibrary(Ljava/lang/String;)V(System.java:924)
	at JNI.main([Ljava/lang/String;)V(JNI.java:3)
	at sun.misc.CVM.runMain()V(CVM.java:514)

Reviewed by Gary